### ISSUE TITLE
Empty subclient results in a KeyError exception

### ISSUE THREAD

**Issue by pertoft** [Commvault/cvpysdk#136]
```
subclients =  self.__commcell.clients.get('vc01.example.com').agents.get('virtual server').instances.get('vmware').backupsets.get('default').subclients..get("empty_subclient")
subclients.browse()
````

Throws an error:
```
Traceback (most recent call last):
  File "/Users/pto/source/commvault-backup-reports/report-jysk-default-subclient.py", line 27, in <module>
    ids, vms = cv.browse()
  File "/usr/local/lib/python3.9/site-packages/neticsdk/commvault.py", line 204, in browse
    return self.__subclient.browse()
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/subclients/vssubclient.py", line 1186, in browse
    vm_ids, vm_names = self._get_vm_ids_and_names_dict()
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/subclients/vssubclient.py", line 1038, in _get_vm_ids_and_names_dict
    return _assign_vm_name_id(self.content, vm_ids, vm_names)
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/subclients/vssubclient.py", line 255, in content
    content = self._get_content_list(children)
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/subclients/vssubclient.py", line 626, in _get_content_list
    vm_id = child['name']
KeyError: 'name'
```
This happens because the code https://github.com/Commvault/cvpysdk/blob/ec40c964eb387f435de53daedf35366608b0001f/cvpysdk/subclients/vssubclient.py#L626
always assumes there are something in a subclient. A simple check should be implemented and an empty result should be returned.

**Comment by pertoft** [comment]
Pull request with a fix opened: https://github.com/Commvault/cvpysdk/pull/137

**Comment by kneerudge** [comment]
Hi Peter,

The fix is in the dev branch, Can you please pull it and check it
https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/subclients/vssubclient.py#L626

**Comment by pertoft** [comment]
Hi 

I have tested with the dev branch:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/neticsdk/commvault.py", line 143, in selectSubclient
    self.__subclient = self.__commcell.clients.get(self.__config['vmware']['vcenter']).agents.get('virtual server').instances.get('vmware').backupsets.get(self.__config['vm']['backupset']).subclients.get(subclientname)
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/client.py", line 3798, in agents
    self._agents = Agents(self)
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/agent.py", line 129, in __init__
    self.refresh()
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/agent.py", line 292, in refresh
    self._agents = self._get_agents()
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/agent.py", line 223, in _get_agents
    raise SDKException('Response', '102')
cvpysdk.exception.SDKException: Response received is empty
```
So I guess the problems is resolved as the .subclients.get() will raise an exception if the subclient is empty.

**Comment by pertoft** [comment]
What are the perspectives for a release with this fix?

**Comment by pertoft** [comment]
There is a problem in the current commit in dev.
```
subclients =  self.__commcell.clients.get(self.__config['vmware']['vcenter']).agents.get('virtual 
server').instances.get('vmware').backupsets.get('defaultBackupset').subclients.all_subclients
```
This always results in 
```
Traceback (most recent call last):
  File "/Users/pto/source/commvault-backup-reports/report-jysk-default-subclient.py", line 17, in <module>
    cv.browseSubclients()
  File "/usr/local/lib/python3.9/site-packages/neticsdk/commvault.py", line 149, in browseSubclients
    subclients =  self.__commcell.clients.get(self.__config['vmware']['vcenter']).agents.get('virtual server').instances.get('vmware').backupsets.get(self.__config['vm']['backupset']).subclients.all_subclients
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/client.py", line 3798, in agents
    self._agents = Agents(self)
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/agent.py", line 129, in __init__
    self.refresh()
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/agent.py", line 292, in refresh
    self._agents = self._get_agents()
  File "/usr/local/lib/python3.9/site-packages/cvpysdk/agent.py", line 223, in _get_agents
    raise SDKException('Response', '102')
cvpysdk.exception.SDKException: Response received is empty
```

**Comment by spakhare** [comment]
Please try this with the latest changes.
