### ISSUE TITLE
main and dev branch broken

### ISSUE THREAD

**Issue by pertoft** [Commvault/cvpysdk#141]
It not possible to get a vmware subclient in dev and main branch. Out commserve is version 11.20.64

````
    subclient = comm.clients.get('vc01.example.com').agents.get('virtual server').instances.get('vmware').backupsets.get('defaultBackupSetTags').subclients.get('Test1')
````
Its working with the current stable in https://pypi.org/project/cvpysdk/
However, the main or dev branch raises an exception exception:
````
Traceback (most recent call last):
  File "/Users/pto/source/commvault-tag-manager/manager.py", line 39, in <module>
    subclient = comm.clients.get('vc01.example.com').agents.get('virtual server').instances.get('vmware').backupsets.get('defaultBackupSetTags').subclients.get('Test1')
  File "/Users/pto/source/commvault-tag-manager/.venv/lib/python3.9/site-packages/cvpysdk-11.26-py3.9.egg/cvpysdk/client.py", line 3804, in agents
    self._agents = Agents(self)
  File "/Users/pto/source/commvault-tag-manager/.venv/lib/python3.9/site-packages/cvpysdk-11.26-py3.9.egg/cvpysdk/agent.py", line 129, in __init__
    self.refresh()
  File "/Users/pto/source/commvault-tag-manager/.venv/lib/python3.9/site-packages/cvpysdk-11.26-py3.9.egg/cvpysdk/agent.py", line 292, in refresh
    self._agents = self._get_agents()
  File "/Users/pto/source/commvault-tag-manager/.venv/lib/python3.9/site-packages/cvpysdk-11.26-py3.9.egg/cvpysdk/agent.py", line 223, in _get_agents
    raise SDKException('Response', '102')
cvpysdk.exception.SDKException: Response received is empty
```

**Comment by spakhare** [comment]
Hi @pertoft,

Can you please confirm if this is working with the latest version?

Thanks

**Comment by pertoft** [comment]
Hi,

I had a session yesterday with Niraj from the Dev team (Ticket 211012-218). It still not possible to restore and edit subclients.

**Comment by spakhare** [comment]
Tracking this via support ticket.
