### ISSUE TITLE
Unable to install on new RHEL 8 with pipenv

### ISSUE THREAD

**Issue by montaropdf** [Commvault/cvpysdk#153]
Hello,

I use pipenv to manage the dependency of my application.

when running `pipenv install cvpysdk`, I got the following error.

```
[evro@lpotladm001a gcloudadm]$ pipenv install cvpysdk
Loading .env environment variables...
Installing cvpysdk...
Error:  An error occurred while installing cvpysdk!
Error text: Looking in indexes: https://repo.gcloud.belgium.be/artifactory/api/pypi/common-pypi-central-remote/simple
Collecting cvpysdk
  Using cached https://repo.gcloud.belgium.be/artifactory/api/pypi/common-pypi-central-remote/packages/packages/d5/98/3f8e69fff5620f5be26fb8edd92f0325f3e41eabdc42d60bd0badc81dd2f/cvpysdk-11.28-py2.py3-none-any.whl (1.1 MB)
Collecting future
  Using cached https://repo.gcloud.belgium.be/artifactory/api/pypi/common-pypi-central-remote/packages/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 11, in <module>
        File "/usr/lib64/python3.8/tokenize.py", line 29, in <module>
          import collections
        File "/usr/lib64/python3.8/collections/__init__.py", line 27, in <module>
          from reprlib import recursive_repr as _recursive_repr
        File "/tmp/pip-install-40o3kdbv/future_bdd6c6e71cac47f99c5f170093bbbf26/src/reprlib/__init__.py", line 7, in <module>
          raise ImportError('This package should not be accessible on Python 3. '
      ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

This is likely caused by a bug in cvpysdk. Report this to its maintainers.
✘ Installation Failed 
```

Strangely enough, the command `pip3 install cvpysdk` succeeds.

Python and pipenv version used:
```
[evro@lpotladm001a gcloudadm]$ python --version
Python 3.8.12
[evro@lpotladm001a gcloudadm]$ pipenv --version
pipenv, version 2022.10.11
```

Any reason why this could fails with pipenv and not with pip?

**Comment by kevinjojeejoseph** [comment]
Hi @montaropdf 
This looks more like an environment issue regarding the future module. I was not able to recreate it on my RHEL 8
Can you please refer this [similar issue](https://github.com/awslabs/aws-lambda-powertools-python/issues/183) while installing future dependency and see if the thread/resolution helps
Let us know if it didn't help

**Comment by montaropdf** [comment]
Hi @kevinjojeejoseph,

Indeed unsetting the PYTHONPATH did the trick during installation of the package. afterward, pipenv does not complain about the `future` module.

Thanks for the help.
