### ISSUE TITLE
UnboundLocalError: local variable 'client_name' referenced before assignment

### ISSUE THREAD

**Issue by tapaskchowdhury** [Commvault/cvpysdk#160]
`def _get_client_from_displayname(self, displayname):` refers to an unassigned 'client_name' variable [see here](https://github.com/Commvault/cvpysdk/blob/dac4634997d3dd3e4dbe7f0f4c838f2a1b4a5b4d/cvpysdk/client.py#L957) causing the following exception: 

```
[ERROR] UnboundLocalError: local variable 'client_name' referenced before assignment
Traceback (most recent call last):
  File "/opt/python/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 150, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/lambda_function.py", line 778, in lambda_handler
    SlmCommvault(slm_utils).bootstrap()
  File "/var/task/lambda_function.py", line 751, in bootstrap
    self._create_commvault_client_group(
  File "/var/task/lambda_function.py", line 333, in _create_commvault_client_group
    status, response = self._create_commvault_client_group_core(
  File "/var/task/lambda_function.py", line 124, in _create_commvault_client_group_core
    virtualization_clients = self._find_virtualization_clients(cloud_name=cloud)
  File "/var/task/lambda_function.py", line 113, in _find_virtualization_clients
    client = self.commvault.clients.get(f"enx{environment.name[0]}z-vms")
  File "/opt/python/lib/python3.9/site-packages/cvpysdk/client.py", line 3347, in get
    client_from_hostname = self._get_client_from_displayname(name)
  File "/opt/python/lib/python3.9/site-packages/cvpysdk/client.py", line 957, in _get_client_from_displayname
    return client_name
```

This could be handled, for example, by replacing the following:

`return client_name
`
with

`return client_name if client_name else None`.  (as this is handled [here](https://github.com/Commvault/cvpysdk/blob/dac4634997d3dd3e4dbe7f0f4c838f2a1b4a5b4d/cvpysdk/client.py#L3353).)

**Comment by kevinjojeejoseph** [comment]
Hi @tapaskchowdhury 
We'd already fixed this on our [dev branch file](https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/client.py#L1017)
I've copied these changes into the master branch with [this commit](https://github.com/Commvault/cvpysdk/commit/d65abb8511315836238944979565d2ddb07633b4)
Thanks
